### ISSUE TITLE
Client QA Updates

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#133] opened 2019-12-16 16:14 UTC
- [x] Add newsletter signup to "News" (category landing page)
- [x] Mapping the Future should be checked by default in the Newsletter signup
- [x] Remove lede image from author landing page template
- [x] Change "And" to "and" on article page main bylines
- [x] Reduce size of top headline on mobile homepage so its more in line with headlines for subsequent stories
- [x] Update byline size on series landing pages so that it matches the sizes on category landing pages
- [x] Change email share to use this format: 

Email Subject is: CityLimits.org: [HEADLINE]

Email Body is: 
From City Limits: 
[HEADLINE]
[DEK]
[Link]

**Comment by joshdarby** [comment] 2019-12-16 16:48
@benlk Do you know if  `$checkedFlag` here is supposed to reset to `false` for every item in `$newsletter`? Right now it sets the first item to `true` and causes every item afterwards to be set to true as well.

https://github.com/INN/umbrella-citylimits/blob/0524a414608499780eede6d186e09f144205c031/wp-content/themes/citylimits/partials/newsletter-signup-maincolumn.php#L25-L48

**Comment by benlk** [comment] 2019-12-16 16:57
I assume it's supposed to reset to false, but it isn't for reasons that look like there's logic that wasn't completed. This is a partial that I did some code-styles cleanup on before we merged https://github.com/INN/umbrella-citylimits/pull/33, but it looks like I missed the checkbox logic.

Would it make more sense to modify the fields to have a "checked by default?" option, which determines whether each newsletter should be checked? This would complement the "active?" option, and could use https://developer.wordpress.org/reference/functions/checked/ to output the checked params.

**Comment by joshdarby** [comment] 2019-12-16 17:00
> Would it make more sense to modify the fields to have a "checked by default?" option, which determines whether each newsletter should be checked?

@benlk Yep, that's what I was thinking. Just wanted to make sure that this was a bug instead of intended behavior before I modified it.

**Comment by MirandaEcho** [comment] 2019-12-17 03:40
@josh - the top story headline on mobile is still too large. It should pretty much match the headlines on the rest of the mobile page.

**Comment by joshdarby** [comment] 2019-12-17 15:18
- [ ] Fix new series landing template widget issue, detailed here: https://github.com/INN/largo/issues/1839
- [ ] Allow selection of empty secondary nav on landing pages
- [ ] Research why Jarrett is not seeing "Series" as an option on the menu tool
- [ ] Remove hardcoded newsletter signup from new series template so they can use the widget instead
- [ ] Allow selection of different menu for open toggled mobile nav

**Comment by joshdarby** [comment] 2019-12-17 16:19
@MirandaEcho The reason Jarrett is not seeing the "Series" option when creating menus is probably because it's not checked under "Screen Options" for his account. I logged into his account on my local environment, checked the box, and the option appears now.

![Screen Shot 2019-12-17 at 10 57 47 AM](https://user-images.githubusercontent.com/18353636/71013617-f7b60e00-20be-11ea-8982-e78fc1643ecd.png)

Should I make that change on his staging account or should we just send him that screenshot and attached instructions on how to do it himself?

**Comment by joshdarby** [comment] 2019-12-17 16:31
@MirandaEcho That's been updated on his account on the staging environment.

**Closed** 2020-02-04 05:19 UTC
Labels: Estimate: <4, Priority: High
